name: Deploy to Lightsail
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Connection Details
        run: |
          echo "Connecting to host: ${{ secrets.LIGHTSAIL_HOST }}"
          echo "Using user: ${{ secrets.LIGHTSAIL_USER }}"

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          key_format: pem
          port: 22
          script: |
            echo "Starting deployment..."
            cd /home/ubuntu/Time-Capsule-project
            # Stop all existing containers
            sudo docker compose down
            # Build and start main service
            sudo docker compose up -d --build

            # Creating topics for kafka
            # Create milestone_topic
            sudo docker exec -it kafka kafka-topics.sh --bootstrap-server localhost:9092 --create --topic milestone_topic --partitions 1 --replication-factor 1
            # Create memory_topic
            sudo docker exec -it kafka kafka-topics.sh --bootstrap-server localhost:9092 --create --topic memory_topic --partitions 1 --replication-factor 1
            # Create comment_topic
            sudo docker exec -it kafka kafka-topics.sh --bootstrap-server localhost:9092 --create --topic comment_topic --partitions 1 --replication-factor 1
            # Create custom_event_topic
            sudo docker exec -it kafka kafka-topics.sh --bootstrap-server localhost:9092 --create --topic custom_event_topic --partitions 1 --replication-factor 1
            # Create historical_event_topic
            sudo docker exec -it kafka kafka-topics.sh --bootstrap-server localhost:9092 --create --topic historical_event_topic --partitions 1 --replication-factor 1
            # Create media_topic
            sudo docker exec -it kafka kafka-topics.sh --bootstrap-server localhost:9092 --create --topic media_topic --partitions 1 --replication-factor 1

            cd memory-service
            sudo docker compose up -d --build
            # Navigate to the main project directory
            cd ..
            # Build and start timeline service
            cd Timeline-Service
            sudo docker compose up -d --build
            cd ..
            # Build and start API gateway
            cd Api-Gateway-Timecapsule
            sudo docker compose up -d --build
            cd ..
            # Build and start auth service
            cd Auth-Servic-Timecapsule
            sudo docker compose up -d --build
            cd ..
            echo "Deployment complete."
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
          LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Debug SSH Connection
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          key_format: pem
          port: 22
          script: |
            echo "Debug: Testing SSH connection"
            whoami
            pwd
            ls -la
          debug: true
