name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }} # Ensure this is set to 'ubuntu'
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Time-Capsule-project
            sudo docker compose down
            sudo docker compose up -d --build
