name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Connection Details
        run: |
          echo "Connecting to host: ${{ secrets.LIGHTSAIL_HOST }}"
          echo "Using user: ${{ secrets.LIGHTSAIL_USER }}"

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          key_format: pem
          port: 22
          script: |
            echo "Starting deployment..."
            cd /home/ubuntu/Time-Capsule-project

            # Bring down any existing services
            sudo docker-compose down

            # Navigate and bring up services in the specified order
            echo "Deploying memory service..."
            cd memory-service
            sudo docker-compose up -d --build

            echo "Deploying timeline service..."
            cd ../Timeline-Service
            sudo docker-compose up -d --build

            echo "Deploying API gateway..."
            cd ../Api-Gateway-Timecapsule
            sudo docker-compose up -d --build

            echo "Deploying auth service..."
            cd ../Auth-Service-Timecapsule
            sudo docker-compose up -d --build

            echo "Deployment complete."

        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
          LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Debug SSH Connection
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          key_format: pem
          port: 22
          script: |
            echo "Debug: Testing SSH connection"
            whoami
            pwd
            ls -la
          debug: true
